Repository ISIS3510-202410-Team-13/Backend, pull requests merged in 2024-04, with the labels that each got.

#16 Initial version of unischedule backend: get endpoints
  GroupsFriendsEvents/Dockerfile
  GroupsFriendsEvents/app.yaml
  GroupsFriendsEvents/package-lock.json
  GroupsFriendsEvents/package.json
  GroupsFriendsEvents/src/index.js
Labels: feature

#19 Script to insert mock data to the db
  BackendDB/insertMockDataBackend.js
Labels: feature

#23 Improve repo readme and structure
  Databases/insertMockDataBackend.js
  README.md
Labels: documentation

#20 Create planner microservice
  .gitignore
  Planner/.gcloudignore
  Planner/Dockerfile
  Planner/README.md
  Planner/api/constants/context_constants.go
  Planner/api/handlers/hello_handler.go
  Planner/api/handlers/planner_handler.go
  Planner/api/middlewares/planner_middleware.go
  Planner/app.yaml
  Planner/cmd/main.go
  Planner/go.mod
  Planner/go.sum
  Planner/models/schedule_model.go
  Planner/services/planner_service.go
  Planner/services/planner_service_test.go
Labels: documentation, feature

#26 Update Index.js: POST user/events endpoint added
  GroupsFriendsEvents/src/index.js
Labels: feature

#28 Add analytics endpoints
  .gitignore
  GroupsFriendsEvents/.gcloudignore
  GroupsFriendsEvents/package-lock.json
  GroupsFriendsEvents/package.json
  GroupsFriendsEvents/src/index.js
  package-lock.json
  package.json
Labels: feature

#27 Add README to GroupsFriendsEvents
  GroupsFriendsEvents/README.md
Labels: documentation
